version: '3.7'
services:
  nethermind:
    image: nethermind/nethermind:latest
    container_name: nethermind
    restart: unless-stopped
    volumes:
      - ./data:/nethermind/data
    command: >
      --config sepolia
      --JsonRpc.Enabled true
      --JsonRpc.Host 0.0.0.0
      --JsonRpc.Port 8545
    ports:
      - "8545:8545"
      - "30303:30303"
